name: budi_rahayu_care_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.0.3
  firebase_core: ^4.2.0
  firebase_storage: ^13.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  google_maps_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  image_picker: ^1.1.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/shared/assets/images/
    - lib/shared/assets/images/logo.png
    - lib/shared/assets/images/foto_hero_section.png
    - lib/shared/assets/images/maps.png
    - lib/shared/assets/icons/
    - lib/shared/assets/icons/instagram.png
    - lib/shared/assets/icons/whatsapp.png
